== CodeConventies

Version history
---------------

[cols=",,,",options="header",]
|=======================================================================
|Version |Date |Person |Note
|V0.1 |05-03-18 |Gerard Zeeman |Created document and added chapter
Hardware Code
|=======================================================================


Preface
-------
1.  Chapter
~~~~~~~
2.  Subchapter
~~~~~~~~~~
3.  Subchapter
~~~~~~~~~~
2.  Hardware
Codefootnote:[https://www.arduino.cc/en/Reference/StyleGuide]
----------------------------------------------------------------------
1.  Coding Style
~~~~~~~~~~~~

Write in the C programming language.

Efficiency is not paramount; readability is.

When forced to choose between technically simple and technically
efficient, choose the former.

Verbose if statements should be used when writing code. This means the
following:

is wrong. Instead this should be used:

The brackets should also be placed like given in the example above.

Pointers should be avoided at all times.

The code should not contain lines that are more than 80 characters long.

The code should use good error detection and handling.

Every time memory is dynamically allocated (e.g. call malloc), there
should be code to free this memory at some other point in the program.

Constants should be used and defined. Constants make the code more
readable and easier to change. For example:

This should not be used: This should be used:

Comments
~~~~~~~~

Comment every variable or constant declaration with a description of
what the variable does.

Comment every code block. Do it before the block if possible, so the
reader knows what's coming.

Comment every for loop.

Every file should start with a command block containing a description of
what the code does.

An example of such comment block is as follows:

Every function should be preceded with a comment block containing a
explanation of the following
functionfootnote:[https://www.cs.swarthmore.edu/~newhall/unixhelp/c_codestyle.html].
An example is:

Any complicated, tricky, or ugly code sequences in the function body
should contain in-line comments describing what it does (here is where
using good function and variable names can save you from having to add
comments).

An example of a correct in-line comment is as follows:

The in-line comment should start one space after the // and should start
with a capital letter.

Variables and Functions
~~~~~~~~~~~~~~~~~~~~~~~

Variable names should be descriptive. Avoid single letter variable
names.

Avoid variable names like val or pin. Be more descriptive, like
buttonState or switchPin.

Variable names should start with an uncapitalized letter and secondary
parts of the name should have a capital letter e.g. buttonState.

1.  Software
Codefootnote:[https://google.github.io/styleguide/cppguide.html]
-------------------------------------------------------------------------
1.  Coding Style
~~~~~~~~~~~~

* Every .cc file should have an associated .h file.
* Header files should be self-contained (compile on their own) and end
in .h. Non-header files that are meant for inclusion should end in .inc
and be used sparingly.
* All header files should have #define guards to prevent multiple
inclusion. The format of the symbol name should be
<PROJECT>_<PATH>_<FILE>_H_.
* Functions should be declared.
1.  Comments
~~~~~~~~

Comment every variable or constant declaration with a description of
what the variable does.

Comment every code block. Do it before the block if possible, so the
reader knows what's coming.

Comment every for loop.

Every file should start with a command block containing a description of
what the code does.

Variables and Functions
~~~~~~~~~~~~~~~~~~~~~~~

Variable names should be descriptive. Avoid single letter variable
names.

Avoid variable names like val or pin. Be more descriptive, like
buttonState or switchPin.

Variable names should start with an uncapitalized letter and secondary
parts of the name should have a capital letter e.g. buttonState.

 +
~~

Web Interface
-------------

 +
--

Bibliography
------------

*The current document contains no sources.*
