include::../Header.adoc[]


image:https://travis-ci.org/ArtOfRobotics/WillyWiki.svg?branch=master["Build Status", link="https://travis-ci.org/ArtOfRobotics/WillyWiki"]

= Welcome

Welcome to project Willy. Before starting the project it is useful to know a few things. Our first advice is to become acquainted with Willy. Follow our Willywiki from begin to end and try to understand how to use Willy. Documentation on the Wiki containts all the details about Willy tot startup the project. If certain details about designdecisions, configuration, hardware or other components about Willy are unclear, more details can be found on google drive. The arhive menu contains links to the google-drive. 

== Status

The table below shows all the milestones and their current status.

[width="100%",options="header,footer"]
|====================
|Milestone  |Researched  |Realized  |Tested  |Category  
|Assessment current status|Done  |Done  |Done  |Documentation  
|Willy Improvisation  |Done  |Done  |Done  |Hardware Software Documentation  
|Design  |Done  |Done  |Done  |Software
|WillyWiki    |Done  |Done  |Done  |Software
|Willy web | Done | Done  | Done  | Software
|Indoor navigation  |Done  |Done  |In progress (fine tuning)  |Software Hardware
|Plating | Done  | In progress |  |Hardware
|Social interaction |Done  |In progress  |  |Software
|====================

=== outdoor navagion

The only thing that has been realized so far with regard to indoor navigation contains GPS. GPS coordinates can be received inside ROS when subscribed on the /GPS topic. 

=== Social interaction
Social interaction is onderzocht. Wij hebben ons als groep gefocused op offline funtionaliteit op verzoek van de opdrachtgever. Offline funtionaliteit is onderzocht; 

https://artofrobotics.github.io/WillyWiki/Research/Social-interaction.html[Research Social Interaction]

Offline spraakherkenning is gerealiseerd door het gebruik van 'Snowboy'. 
