=== Leap advice

Navigating trough the web platform will be supported by the leap. There are several packages examined, and the following where tested.

* desktopLeapr
* Pyleapmouse
* Xleapmouse
* Leap_motion ROS
* Mudra mouse
* Leap touch

==== DesktopLeapr
DesktopLeapr runs on python. It can be cloned from Git and requires several dependencies. DesktopLeapr can be used to move the mouse cursor with the Leap, also click functionality can be realized by detecting certain gestures.  However it not user friendly, it has a lot of features and is very advanced. The goal is that a passerby immediately understands how he can interact with willy, so customization is required.

==== Pyleapmouse
Pyleapmouse is comparable with Desktopleapr in functionality. After installation, we have tested the functionality of Pyleapmouse. However functionality also is not straight forward and reliable. 

==== Xleapmouse
Pyleapmouse is rewritten in C++ and is called Xleapmouse. After installation of Xleapmouse, we got a lot of error messages. After a few hours of troubleshooting we clancled testing. 

==== Leap_motion ROS
Leap_motion ROS can used to connect the leap with the ROS framework. however it only delivers coordinates when subscribed. So customization is required. 

==== Mudramouse
Mudramouse is easy to install and works very well. The mouse cursor can be moved with the Leap and with a certain gesture, click functionality can be realized. However it is not free to use and close source. 

==== Leap touch (chrome plugin)
Leap touch comes with the same functionality as Mudramouse, however Leap Touch works as a browser plug-in. For our project, this is a advantage because the web browser cannot be closed with the leap touch plug-in. Also functionality is customizable. The only disadvantages are that it is also closed source and functionality feels a little less natural compared with Mudramouse.



