include::../Header.adoc[]

== Driving of willy
=== Steps for autonomous driving
These steps will start the autonomous driving of willy. Do you want to drive manually by using the keyboard? 
Then take a look at the steps for manual driving underneath.

1. **Deploy the brakes** +
To start Willy, the brakes need to be deployed. Otherwise, Willy will not be able to drive. 
To deploy the brakes you have to use the levers on the front of the motors. 
You can check if the brakes are deployed by trying to push Willy. 
The brakes are applied when the wheels can't rotate anymore.

2. **Turn the power on** +
Willy needs power to be able to operate. 
Make sure the power levers on the side of Willy are both turned on (under the voltage display).

3. **Turn the motor controller off** +
Willy cannot start when the motors are turned on. 
To turn the motor controller off, use the switch on the bottom of the pc case. (or the emergency button for convenience)

4. **Start Willy by running the startup command** +
Willy is now able to start. You can easily start willy by running our startup package.
To run this package, navigate to the following directory: +
`/home/willy/Documents/willy` +
Run the following command to initialize willy, make sure that internet is available since it may need extra software packages: +
`./init-willy.sh` +
Finally run start command: +
`./start-willy.sh` +
Willy will now start the software and hardware to start the autonomous driving project. +

IMPORTANT: Do not forget to release the emergency stop when the steps above are finished. Otherwise willy will not drive.

=== Steps for manual driving 

To manually drive willy, follow the steps in 'autonomous driving'. Before releasing the emergency stop button make sure the playstation controller is connected. To initialize the controller press and hold the home button until the status lights stop blinking and has 1 steady light.

After releasing the emergency you can take control over the robot by giving input with the left joystick while holding the select button. The robot will prioritize manual input over autonomous input. Once you stop giving input the robot will resume autonomous driving 