include::../Header.adoc[]

== Development

=== Important information

Willy is based on various ROS nodes. These are called Willy components. For example: Sonar, Lidar, Kinect.
Before starting developing for Willy, be aware of this infrastructure which is used to run the complete system.

There are basically two ways of developing new features for Willy: +

. Create and develop a new Willy component
. Extend and develop within an exisiting Willy component

A valid Willy component complies with the following Prerequisites: +

. A Dockercompose file +
*A docker-compose file to define the services for this component. This docker-compose file contains only the needed containers for this component (This services will be extended in the main repository)*
. At least one service referenced in the Dockercompose file +
*Define at least one service for this container, but when the component requires multiple services define all the needed services for this container.*
. A README file with the component description +
. A Travis file with the CI configuration +
. A valid documentation on the WillyWiki +

=== New component

NOTE: To start development, make sure you complies to the requirements above.

==== Create new component

. Login on: +
`https://github.com/Windesheim-Willy`

. Create a new repository with the following naming format: +
`your_component_lowercase_with_underscore_seperator`

. Clone the repository: +
`git clone https://github.com/Windesheim-Willy/your_component_lowercase_with_underscore_seperator.git`

. Go to the location of your repository: +
`cd your_component_lowercase_with_underscore_seperator`

. Create a new development branch: +
`git checkout -b feature/init-component`

. Add a README.md file(example):
+
[source,md]
-----------------
# Keyboard

[![Build Status](https://travis-ci.org/Windesheim-Willy/keyboard.svg?branch=master)](https://travis-ci.org/Windesheim-Willy/keyboard)

The keyboard is a node that can process the raw input information to the keyboard topic.

For more information, check out the wiki about the keyboard [Wiki](https://windesheim-willy.github.io/WillyWiki/Components/keyboard.html)
-----------------

. Add a .travis.yml file(example):
+
[source,yml]
-----------------
sudo: required

language: ruby

services:
  - docker

script:
  - docker-compose -f docker-compose.yml -f docker-compose.build.yml build
-----------------

. Add a docker-compose.build.yml file(example):
+
[source,yml]
-----------------
# Override compose file for ROS-master with local build of the container.
    version: '2.1'
    
    services:
      sonar:
      
    build: ./docker
-----------------

. Add a docker-compose.yml file(exmaple):
+
[source,yml]
-----------------
# Main compose file for ROS-master with the container from Dockerhub.
version: '2.1'

services:
  <component name>:
    image: windesheimwinny/<component name>:latest
    networks:
      - ros
    restart: always
-----------------
. Add a folder with the name "docker"
. Add a file with the name "Dockerfile" without extension(example):
+
[source,yml]
-----------------
FROM ros:kinetic
-----------------
. Commit and push the changes: +
`git add .` -> `git commit` -> `git push`
. Create a pull request on the component master branch

==== Integrate new component

. If you do not have a clone of the Willy respository yet, clone the repo first: +
`git clone https://github.com/Windesheim-Willy/willy.git`
. Verify to checkout the master, unless you need another branch: +
`git checkout master` 
. Add your module to the .gitmodule file(example *url* and *path*): +
`git submodule add https://github.com/Windesheim-Willy/<component name>.git components/<component name>`
. Load the submodule into the repository: +
`git submodule update --recursive --remote`


=== Exisiting component
NOTE: To start development, make sure you complies to the requirements above.

. Clone the component repository via the wiki url: +
`git clone https://github.com/Windesheim-Willy/component.git`
. Go to the repository location: +
`cd component`
. Checkout the master branch: +
`git checkout master`
. Create a new development branch from master: +
`git checkout -b feature/hello-world`
. Develop something...(example): +
`echo "Hello world!!" > helloWorld.txt`
. Check git status of changes: +
`git status`
. Add all or specific changes: +
`git add .`
. Git commit: +
`git commit`
. Push your branch to the remote, if not pushed yet use the upstream origin parameter: +
`git push --set-upstream origin feature/hello-world`
. Create a pullrequest on master and merge the branches


=== Willy environment

Integrate your component within the global willy system (only if you created a new component) or update the components if any development has been made on one of them.

==== Add new component
. Clone the branch of the repo "willy": +
`git clone https://github.com/Windesheim-Willy/willy.git`
. Verify to checkout the master, unless you need another branch: +
`git checkout master` 
. Create and checkout new branch: +
`git checkout -b feature/add-component_name`
. Add your module to the .gitmodule file(example *url* and *path*): +
`git submodule add https://github.com/Windesheim-Willy/<component name>.git components/<component name>`
. Load the submodule into the repository: +
`git submodule update --recursive --remote`
. Add all or specific changes: +
`git add .`
. Git commit: +
`git commit`
. Push your branch to the remote, if not pushed yet use the upstream origin parameter: +
`git push --set-upstream origin feature/add-component_name`
. Create a pullrequest on master and merge the branches

==== Update exisisting component

. Update a specific component in the willy repository: +
`git submodule update --init componentname`
. Update all components in the willy repository: +
`git submodule update --recursive --remote`

=== Component documentation

When a new component is created or a exisisting component has been modified, one has to bring the WillyWiki up-to-date so everybody can read about what a component does and why it's there.

. Clone the branch of the repo "WillyWiki": +
`git clone https://github.com/Windesheim-Willy/WillyWiki.git`
. Verify to checkout the master, unless you need another branch: +
`git checkout master` 
. Create and checkout new documentation branch: +
`git checkout -b feature/component-documentation`
. Go to the components folder and create or choose a .adoc file: +
`Components/component.adoc`
. Add or edit information on behalf of your development (Lidar example): +
+
[source,adoc]
-----------------
include::../Header.adoc[]

== Lidar
The lidar is a node to process the raw lidar information to the lidar topic.

=== Repository
====
https://github.com/Windesheim-Willy/lidar[Windesheim-Willy/lidar, role="external", window="_blank"]
====

=== How to run?
To run only the lidar the Docker can be used. The Dockerfile for the lidar is automatically built on Dockerhub.

====
https://hub.docker.com/r/windesheimwinny/lidar[windesheimwinny/lidar, role="external", window="_blank"]
====

Run the build docker image:

[source,shell]
----
docker-compose up
----

For development purposes it can be usefull to build the Dockerfile locally and to use this image. The docker-compose.build.yml file builds first the image and after the build start the container.

[source,shell]
----
docker-compose -f docker-compose.yml -f docker-compose.build.yml up
----
-----------------
. Save the file
. Go to the root folder and open the sidebar.adoc file: +
`WillyWiki/sidebar.adoc`
. Add your component or check if your component reference already exists in the section [Components]: +
+
[source,adoc]
-----------------
link:{url}/Components/index.html[Components]::
        - link:{url}/Components/Development-guide.html[Development Guide]
        - link:{url}/Components/willy.html[Willy main]
        - link:{url}/Components/ROS-master.html[ROS master]
        - link:{url}/Components/brain.html[Brain]
        - link:{url}/Components/sonar.html[Sonar]
        - link:{url}/Components/kinect.html[Kinect]
        - link:{url}/Components/lidar.html[Lidar]
        - link:{url}/Components/motor_controller.html[Motor controller]
        - link:{url}/Components/new_added_component.html[New component]
-----------------
. Save the sidebar.adoc file
. Add all or specific changes: +
`git add .`
. Git commit: +
`git commit`
. Push your branch to the remote, if not pushed yet use the upstream origin parameter: +
`git push --set-upstream origin feature/component-documentation`
. Create a pullrequest on master and merge the branches



