include::../Header.adoc[]

== Development

NOTE: To start development, make sure you complies to the requirements above.

=== Important information

Willy is based on various ROS nodes. These are called Willy components. For example: Sonar, Lidar, Kinect.
Before starting developing for Willy, be aware of this infrastructure which is used to run the complete system.

There are basically two ways of developing new features for Willy: +

- Create and develop a new Willy component
- Extend and develop within an exisiting Willy component

A valid Willy component complies with the following Prerequisites: +

- A Dockercompose file +
- At least one service referenced in the Dockercompose file +
- A README file with the component description +
- A Travis file with the CI configuration +

=== New component

==== Create new component

- Login on: `*https://github.com/Windesheim-Willy*`
- Create a new repository with the following naming format:  `*your_component_lowercase_with_underscore_seperator*`
- Clone the repository: `*git clone https://github.com/Windesheim-Willy/your_component_lowercase_with_underscore_seperator.git*`
- Go to the location of your repository: `*cd your_component_lowercase_with_underscore_seperator*`
- Create a new development branch: `*git checkout -b feature/init-component*`
- Add a README.md file:

[source, md]
----
# Keyboard

[![Build Status](https://travis-ci.org/Windesheim-Willy/keyboard.svg?branch=master)](https://travis-ci.org/Windesheim-Willy/keyboard)

The keyboard is a node that can process the raw input information to the keyboard topic.

For more information, check out the wiki about the keyboard [Wiki](https://windesheim-willy.github.io/WillyWiki/Components/keyboard.html)
----


- Add a .travis.yml file:

[source,yml]
----
sudo: required

language: ruby

services:
  - docker

script:
  - docker-compose -f docker-compose.yml -f docker-compose.build.yml build
----

- Add a docker-compose.build.yml file:

[source,yml]
----

# Override compose file for ROS-master with local build of the container.
    version: '2.1'
    
    services:
      sonar:
      
    build: ./docker
----    
- Add a docker-compose.yml file
- Add a folder with the name "docker"
- Add a file with the name "Dockerfile"
- Commit and push the changes
- Create a pull request on the component master	

==== Integrate new component


=== Exisiting component

1. Clone the component repository via the wiki url.
2. Checkout the master branch
3. Create a new development branch from master
4. Develop something...
5. Git commit
6. Git push your branch
7. Create a pullrequest on master
	

=== Willy environment

Integrate your component within the global willy system (only if you created a new component)

1. Checkout the master branch of the repo "willy"
2. Create and checkout new branch "git checkout -b feature/add-component"
3. Open the .gitmodules file
4. Add a reference to your new component repository
5. Pull all components "git submodule update --init --recursive"
6. Commit your changes
7. Push your branch
8. Create a pull request on the master branch



