include::../Header.adoc[]

== Social interaction
The social interaction creates the interaction of Willy. He listens and speaks with people.

More information about the social interaction see link:{url}/WEB/Interaction.html[Social Interaction].

=== Repository
====
https://github.com/Windesheim-Willy/social_interaction[Windesheim-Willy/social_interaction, role="external", window="_blank"]
====

=== How to run?
To run only the social interaction the Docker can be used. The Dockerfile for the social interaction is automatically built on Dockerhub.

====
https://hub.docker.com/r/windesheimwinny/social_interaction[windesheimwinny/social_interaction, role="external", window="_blank"]
====

Run the build docker image:

[source,shell]
----
docker-compose up
----

For development purposes it can be usefull to build the Dockerfile locally and to use this image. The docker-compose.build.yml file builds first the image and after the build start the container.

[source,shell]
----
docker-compose -f docker-compose.yml -f docker-compose.build.yml up
----

=== Nodejs packages (npm)
Never run `npm install` outside the Docker container to prefent OS conflicts between the Nodejs packages.

Run the npm install command:
[source,shell]
----
docker-compose run social_interaction npm install
----

=== Stylesheets
The source files for the stylesheet are written in SASS. The should be compiled to CSS files what a browser can process.
Gulp compiles the SASS files to CSS files.

Compile only once the SASS file:
[source,shell]
----
docker-compose run social_interaction npm run sass:build
----

Compile the SASS file on every file change:
[source,shell]
----
docker-compose run social_interaction npm run sass:watch
----
