include::../Header.adoc[]

== Willy main
This repository is the main repostitory of Willy. All the different components
of Willy are connected in one Docker network inside this repository.

For more information about the initial setup, check out the link:{url}/Config/index.html[wiki about the configuration]::

== Repository

====
https://github.com/Windesheim-Willy/willy[Windesheim-Willy/willy, role="external", window="_blank"]
====

==== Git submodules

====
https://git-scm.com/book/nl/v2/Git-Tools-Submodules[Documentation about git submodules, role="external", window="_blank"]
====

===== Add new sub module

[source,shell]
----
git submodule add <GIT URL> <FOLDER NAME>
----

===== Keep submodules up-to-date

When updating submodules for the first time, use:

[source,shell]
----
git submodule update --init --recursive
----

When updating the current submodule branches, use:

[source,shell]
----
git submodule update --recursive
----

When updating all submodules with the latest commits on the supermodule, use:

[source,shell]
----
git submodule update --recursive --remote
----

=== How to run?

Run the build docker image:

[source,shell]
----
docker-compose up
----

=== How to manage the containers?
Portainer gives a central overview of the Willy Docker host. From the dashboard, you can access and manage the containers for Willy. Portainer has access to the logs, container settings, performance and gives console access to the container.

When the Willy Docker compose is running the portainer container is accessible from link:http://localhost:9000[localhost:9000]

More information about portainer, see link:https://portainer.io/overview.html[portainer.io]
