include::../Header.adoc[]

== Willy

=== Project background and progress

In 2015 a 'waste competition' was organized at a primary school, with the aim to provide the 
pupils of this primary school with a solution to the question 'how to keep the Grote Markt in 
Zwolle clean'. Eventually, six students won this competition with their idea to keep the Grote 
Markt clean with the help of a 'cleaning robot (Willy)'. An important aspect of Willy had to 
be that he would be able to interact with bystanders and thus influence them on their waste 
behavior. For example, Willy might point out to people that it would be better to deposit 
waste in a waste bin instead of throwing it on the floor; this would enable Willy to 
influence people positively. In short, Willy must be able to act in a corrective as well as 
a preventive (i.e. interaction) manner.

The primary school contacted the township of Zwolle to see if the 'Willy concept' could be 
realized. The township of Zwolle reacted positively to the Willy concept and then looked 
into whether it could involve a partner who could take on Willy's realization.

Eventually the township of Zwolle found 'The Art of Robotics (TAoR)'; a foundation 
that works to increase the awareness of robot technology in today's society. ' The team of 
TAoR responded enthusiastically to this proposition and subsequently made a plan on how they 
could best realize Willy. Ruud van der Burg contacted Hogeschool Windesheim on behalf of 
TAoR with the proposal to see if it would be possible to let students (of different 
disciplines) work at Willy. Windesheim has agreed to this, with which the realization process 
of Willy started.

In order to be able to actually realize Willy, the development process was chopped into 
various iterations, with the result that different training disciplines would start working 
on the creation of Willy. In principle, students from IPO (Industrial Product Design) worked 
on a graphic design of Willy, which would make it clear what Willy should look like. They 
have also been involved in making technical drawings with regard to the frame to be realized 
and other design aspects.

The students (mechanical engineering), of the second iteration, have occupied themselves with 
the realization of a moving chassis for Willy. In the end they decided that the undercarriage 
of an electric wheelchair would be the best option and so they purchased and prepared this 
for further developments.

During the third iteration, HBO-ICT students have been working on realizing the autonomous 
functionality of Willy. An important characteristic of Willy is, that he must be able to 
function completely autonomously on the Grote Markt in Zwolle (this is a further feature of 
functionality that Willy should also be able to function in buildings). This meant in the 
first instance that the project group had to deal with determining the right kind of sensors. 
Without sensors it would be impossible to recognize objects and therefore avoid them. These 
sensors eventually had to be linked to Willy's Operating System (ROS). This project group has 
also been involved in writing an algorithm, which Willy will be able to drive a fixed pattern 
within a defined area.
