include::../Header.adoc[]

== Willy Git setup
Commands used to set up the git repos in willy.

[source,text]
----
cd /home/willy/Documents
git clone https://github.com/Windesheim-Willy/WWEB
cd WWEB
git checkout -b test
git push -u origin test
-	Username: willythegarbagedisposal@gmail.com
-	Password:
cd ..
git clone https://github.com/Windesheim-Willy/WTGD
cd WTGD
git checkout -b test
git push -u origin test
-	Username: willythegarbagedisposal@gmail.com
-	Password:
----

==== Github synchronisation
A crontab has been created which ensures that Willy stays up-to-date with Github. Because Willy does not have a fixed external-IP or domain, it is unfortunately not possible to use Github Webhooks. That is why a crontab job has been set up, which is configured as follows:

[source,text]
----
sudo crontab -e

*/1 * * * * su -s /bin/sh -c '/home/willy/Documents/WTGD/bin/gitsync.sh ' >> /home/willy/Documents/logs/git.log 2>&1
----

The script used for syncing github can be found on link:https://raw.githubusercontent.com/Windesheim-Willy/WTGD/test/bin/gitsync.sh[Github]. The main purpose of the script is to do the following:

* Update the WTGD code for driving
* Set permissions for script folder
* (In the future): automatic building
* Update the WWEB code for web platform
* Set permisions for specific folders


[Note]
--
Currently this line creates a pull of the test branch, later it is desirable to change this to the master branch for production code.
Logs can be found in:
/home/willy/Documents/logs/git.log
--

[TIP]
--
To track the status of git sync live use the following command
[source,text]
----
tail -f /home/willy/Documents/logs/git.log
----
--

==== Github Repo Willy
Can be found in /home/willy/Documents/WTGD

==== Github Repo Web platform
Can be found in /home/willy/Documents/WWEB

==== Build
*Web interface*
For building the web interface refer to the link:{url}/WEB/Development-guide.html[Development Guide] of the Web section.

*Willy*
For building the software used by Willy refer to the link:{url}/Technical/Development-guide.html[Development Guide] of the Technical section.

==== Accounts
All the accounts coupled to the email adress: willythegarbagedisposal@gmail.com can be found on the Google Drive


[bibliography]
=== References
- link: {url}/Documents/#_willy_git_setup
