[cols=",",options="header",]
|=======================================================================
|*General*
|*Date * |19-03-2018

|*Project name* |Project ‘Willy’

|*Students’ names* a|
Vincent van Dijk

Jesse Bouwman

Jonathan ten Hove

Martijn van Olst

Gerard Zeeman

|*Days worked per student* |Vincent: 4

| |Jesse: 4

| |Gerard: 5

| |Martijn: 5

| |Jonathan: 4

|*Total days worked per student* |Vincent: 27

| |Jesse: 29

| |Gerard: 25

| |Martijn: 30

| |Jonathan: 29

|*Progress*

|_Mention in this form (*per student*) what you did this week, what is /
is not going well and any other details. Mention your work planned for
the next week and whether you are on schedule, and reflect briefly on
learning situations. Don’t forget teamwork, learning moments etc. _
|=======================================================================

[cols="",options="header",]
|=======================================================================
a|
Last week done:
~~~~~~~~~~~~~~~

*Vincent:*

Update Ubuntu

Update ROS version

Reinstallation Ubuntu

Refurbishment Ubuntu

Investigate alternative interaction

*Jesse:*

Investigate alternative interaction

Communication Beta technique day

Planning MS project

Trello updaten

*Martijn:*

Sensors wires structure confirmation

Order and confirm USB hub

Controlling Joycontroller

*Jonathan:*

Inventory web platform

Wifi on Willy

Rosframework inventory

Review documentation

*Gerard:*

Sensors wires structure confirmation

Order and confirm USB hub

Controlling Joycontroller

Review documentation

a|
Brief reflection on learning opportunities:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

_Below we have devised a number of points for improvement that apply to
our group_

__________________________________________
_- Communicate better when problems arise_

_- Plan better_

_- Do not forget Daily standup_

_- Complete the inventory report_

_- learn from last week's reporting_
__________________________________________

a|

What is going well?
~~~~~~~~~~~~~~~~~~~

*Jesse:*

Communication with external parties. Also working via trello is well
guarded by Jesse. The research into alternative interaction was
completed in time by Jesse.

*Martijn:*

Collaboration with group members went smoothly. Writing required code
went very smoothly.

*Jonathan:*

Jonathan has a good insight into the overvieuw of the web platform and
the underlying relations between the different programming languages.

*Gerard*

Gerard has made the hardware orderly and reliable. He has also been able
to support Martijn in the development of the Joycontroller

*Vincent*

Has been able to reinstall both the Ros and the Ubuntu platform through
the current inventories.

a|
What are the bottlenecks and (possible) solutions?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The new Ubuntu version is not yet stable. Also the Joycontroller has to
be more reliable.

a|
To do next week:
~~~~~~~~~~~~~~~~

Settings new sprint goals and improving Ubuntu by a clean installation
with current configuration and further development of the Joycontroller.

|=======================================================================

Bibliografie
------------

Notes Retrospective 1 (3 6, 2018).
