include::../Header.adoc[]

== ToDo
=== Indoor navigation

Indoor navigation was realized with the use of a lidar and ultrasonic sensors. Willy can map a space and plan routes within it. The following features and improvements are recommended:

* Fine-tune indoor navigation
* Indoor navigation localization registration;
Remember where Willy was in a certain room so he explores new places first.
* The storage and loading of previously mapped spaces and recognizing Willy's current location for further navigation.
* Navigating in spaces with a large audience. Recognizing moving objects and making decisions based on this.

=== Outdoor navigation

The only thing that has been realized so far with regard to outdoor navigation is GPS and the compass. GPS coordinates can be received inside ROS when subscribed on the /GPS topic. 

* Location based on GPS
* Visualize GPS location.
* Accessibility determination based on location
* Route determination based on GPS and location determination
* Indoor navigation localization registration to keep Willy within a certain area.


=== Social interaction
Social interaction has been investigated. As a group we have focused on offline functionality at the request of the client. Offline functionality has been investigated; 
https://artofrobotics.github.io/WillyWiki/Research/Social-interaction.html[Research Social Interaction]

Offline wakeword recognition has been realized through the use of 'Snowboy'. Documentation about Snowboy can be found on;
http://docs.kitt.ai/snowboy/[Snowboy Documentation].

Implementation of Snowboy on Willy is described here;
https://artofrobotics.github.io/WillyWiki/Config/index.html#_install_snowboy



