include::../Header.adoc[]
==== Notulen 9-2
Tweede gesprek met Ruud

==== Projectdoel

* Willy heeft een stabiele basis en configuratie
* Willy rijdt autonoom rond binnenshuis
* Willy heeft sociale interactie
* Willy heeft enigszins een frame wat aansluit op het ontwerp waar
andere groepen mee verder kunnen gaan
* Willy met een wauwfactor kunnen presenteren op Winnovation

==== Sprintdoel

* Stabiele configuratie van Willy

==== Backlog

==== Frame

* Inventarisatie wat er nu is
* Ontwerp
** Rekening houden met koeling en plaatsing sensoren
* Kap ter bescherming
* Onderzoek/Plan voor werktuigbouwkunde wat er gedaan kan worden

==== Hardware

* Inventarisatie onderdelen
* Inventarisatie Code
* Onderzoek accu’s
* Onderzoek backup interactie (touchscreen)
* Onderzoek vervanging scherm

==== Software

* Update ROS framework
* Update Linux platform
* Onderzoek lidar
* Onderzoek algoritmes autonoom rijden

Ruud

* Contact met Sick
* Contact met Deltion
* Contact met Windesheim
* Lidar ophalen
* Vervolggesprek 22 februari

==== Notities

Adres Ruud: Maatgravenweg 4, Zwolle

Marcel heeft het frame ontworpen en bedacht op welke plek de onderdelen
komen, wij moeten dit opnieuw bekijken en waar nodig veranderen en/of
uitbreiden. Ruud benoemd dat eerst het idee was om een lade te maken met
daarin de elektronica maar geeft aan dat we hier opnieuw naar moeten
kijken ook met koeling in gedachten.

Wij geven aan dat we aanlopen tegen allemaal tijdelijke oplossingen en
niet een geheel. Ruud geeft aan dat het hebben van een stabiel platform
prioriteit 1 is.

Wij geven aan dat we eerst een inventarisatie willen van wat er nu staat
en hoe het werkt en geven aan enthousiast te zijn over het project.

Wij onderzoeken huidige ROS versie en concluderen als update nodig is
ook met toekomst in gedachten.

Ruud geeft aan dat we moeten onderzoeken of de accu’s die naar voren
komen in voorgaande documentatie nog steeds de juiste keuze zijn. Daarna
kunnen we met korte argumentatie ruud vragen om sponsors te zoeken voor
de nieuwe accu’s.

Ruud geeft aan dat er onderzoek gedaan is naar zwaartepunt en dergelijke
van de robot en berekeningen zijn gedaan. Alleen is dit gedeelte niet
gedocumenteerd en heeft degene die daarmee bezig is geweest dit ook niet
afgemaakt.

Ruud geeft aan dat kabels door het frame niet gewenst is in het geval
dat er later aangelast moet worden.

Ruud geeft aan dat het doel van het project belangrijk is en deze
beweegt tussen vastgestelde grensen, na elke sprint moeten we beoordelen
hoe we ten opzichte van het doel er voor staan.

Ruud geeft aan dat de wauwfactor van groot belang is voor het doel wat
je wilt neerzetten. Als wij zelf construdtie-elementen toevoegen zal dit
bijdragen aan de wauwfactor, denk aan het uiterlijk.

Ruud geeft aan dat we in gesprek met Sick ook ROS moeten benoemen, zodat
zij mogelijk een oplossing kunnen aandragen.

Ruud geeft aan contact op te nemen met het Deltion voor het maken van de
Vormdelen, omhulsel van kunstof.

Werktuigbouwkunde gaat bezig met het stofzuigergedeelte maar wij moeten
met een plan komen en kijken wat wertuigbouwkunde kan gaan doen.

Ruud geeft aan dat het doel van het project ook zelfstandig binnen
rijden is en de huidige functionaliteit van autonoom rijden alleen het
ontwijken van wat hij tegenkomt op zich neemt. Ook kunnen we zelf kijken
als er mogelijk al algoritmes te vinden zijn die we kunnen gebruiken om
autonoom te rijden. Henk van fontis heeft ervaring met AGF systemen en
hier kunnen we gemakkelijk mee in contact worden gebracht als we hulp
nodig hebben bij autonoom rijden.

Het ontwerp van IPO is gedateerd hier zullen we zelf opnieuw naar moeten
kijken en aanpassen.

Ruud geeft aan dat we sponsoren nodig hebben om middelen te verkrijgen,
wij moeten de sponsoren wel iets kunnen bieden. Zoals bijvoorbeeld een
spraak en antwoord model dat past bij de sponsor zodat ze dat misschien
op een beurs kunnen gebruiken.

Wij geven aan dat we een divers team hebben met achtergrond in
werktuigbouwkunde en iemand die werkt in de bouwmarkt en iemand die zijn
eigen cart bouwt.

Ruud benoemd voordat we verdergaan met het project dat we een kap moeten
hebben ter bescherming. En geeft aan dat we de bonnen daarvan naar hem
kunnen sturen.

Ruud geeft aan dat als we het scherm vervangen deze de zelfde impact
moet hebben als in het ipo ontwerp.
