include::../../../Header.adoc[]
=== Screen

[discrete]
==== Version history

[cols=",,,",options="header",]
|===========================
|Version |Date |Person |Note
|V0.1 |04-02-18 |Jesse |
|===========================

==== Preface

This document is about the research of the possibility to get a new
screen on Willy. The reason for a new screen is that the current screen
is a screen that uses 130 Watt. The last project group noticed that the
batterie level drained fast when using the screen.

==== Current screen

The current screen is a Smit Visual Touch LCD panel with the following
specifications:

[cols=",",options="header",]
|=============================================
|*Brand* |*Smit Visual*
|*Type* |Focus Touch LCD monitor 42”
|*Touch* |Yes
|*Response time* |6,5 milliseconds
|*Brightness* |500 cd/m2
|*Resolution* |1920 * 1080 pixels
|*DVI* |1
|*Power usage* |130W
|*Backlight* |LCD
|*Length / Width / Height* |104,5/63,5/14 (cm)
|=============================================

A problem with this screen is that it runs on 230V. It needs a converter
to supply the necessary voltage. The converter has an efficiency of
roughly 60%. The actual power which is used to use the screen is 130W *
1.4 = 182W.

==== New screen

A new screen has to be more efficient than the current screen. Because
of that it’s wise to look at a LED screen which uses an adapter. With
this we exclude the 230V converter and the power usage of the screen
decreases dramatically.

When Willy uses a LED screen of 42 inch without the converter, it uses
roughly 60 watt. This means we use 32% of the current used energy.

Willy needs a way to interact with people and for that the current
screen uses touch. There will be a research about other ways to interact
with people. Because of this the next screen doesn’t have to be a
touchscreen. This makes the screen more affordable.

One of the possibilities is the LG-43LJ5150. This is a 43 inch screen
with the following specifications:

[cols=",",options="header",]
|===============================================
|*Brand* |*LG*
|*Type* |43LJ5150
|*Touch* |No
|*Resolution* |1920 * 1080 pixels
|*Connection* |HDMI 2x, USB
|*Power usage* |42W
|*Backlight* |Direct-LED
|*Length / Width / Height* |110,8/65,7/6,95 (cm)
|===============================================

This tv needs the converter. The total power consumption will be 42W*1.4
=58,8W.

==== Advice

The advice is to look for a second hand 42 inch tv screen without touch.
These are affordable and use a lot less energy than the current screen.
It would be handy to use a tv which uses a power adapter so Willy don’t
has to use the external converter. Even if there is a new screen, like
the one stated in chapter three, the power consumption decreases by more
than 60%.

==== References

- LG. (n.d.). _Televisies_. Retrieved from lg.com:
http://www.lg.com/nl/televisies/lg-43LJ5150salland.eu. (n.d.).
- _smit-visual-focus-touch-lcd-monitor_. Retrieved from Salland.eu:
https://www.salland.eu/product/710817/smit-visual-focus-touch-lcd-monitor-42i-42-inch-106-6-cm-full-hd-14029-210.html
