include::../Header.adoc[]

== Development Guide

=== Prerequisite

* Basic knowlegde of NodeJs, Git and ROS

* Install Git & Editor +
https://code.visualstudio.com/
* Install NodeJS +
https://nodejs.org/en/download/

* Install Sails
[source,bash]
npm install sails -g
* If on Windows:
. Install Ubuntu
- Got to Microsoft store
- Search for 'Ubuntu'
- Click get/install
. Install ROS
- Follow ROS Kinetic installation + (this might take some time)
http://wiki.ros.org/kinetic/Installation/Ubuntu
[source,bash]
sudo apt-get install ros-kinetic-desktop-full
- And enviroment setup
[source,bash]
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc
- Test the installation running ROS
[source,bash]
roscore
- Done for now
[source,bash]
(ctrl+c)

=== Github
* Invite your personal Github account to acces Windesheim-Willy repos
https://github.com/orgs/Windesheim-Willy/people
* Clone Git Repo
[source,bash]
git clone https://github.com/Windesheim-Willy/WWEB
* Switch to test branch
[source,bash]
git checkout -b origin/test

=== Compilation
Compilation is done via catkin, this is done to create a rospackage so that nodejs can run in a ROS enviroment.
[source,bash]
cd WWEB/src
npm install
cd ..
source /opt/ros/kinetic/setup.bash
catkin_make

=== Testing/Debugging
*Run without ros:*
[source,bash]
----
cd WWEB/src
sails lift (or node app.js)
----
*Run with Ros:*

. Start Roscore

- Open a terminal (Ubuntu app on windows)
-
[source, bash]
cd WWEB
source devel/setup.bash
roscore

. Run webplatform
- Open a terminal (Ubuntu app on windows)
-
[source, bash]
cd WWEB
source devel/setup.bash
rosrun willyweb start.sh

[NOTE]
--
The rosrun command might not have acces to port 80 for this to work use sudo -s
[source,bash]
----
sudo -s
rosrun willyweb start.sh
----
--

=== Running Scripts
In the same manner as you would do <<Testing/Debugging>> you can also run scripts.
Scripts are located in the folder 'WWEB/src/scripts'.

. Start Roscore

- Open a terminal (Ubuntu app on windows)
-
[source, bash]
cd WWEB
source devel/setup.bash
roscore

. Run sending script
- Open a terminal (Ubuntu app on windows)
-
[source, bash]
cd WWEB
source devel/setup.bash
rosrun willyweb scripts/send.js

. Run receive script
- Open a terminal (Ubuntu app on windows)
-
[source, bash]
cd WWEB
source devel/setup.bash
rosrun willyweb scripts/receive.js

[NOTE]
--
Rosrun makes it possible to communicate with ROS because it is now run as a ROS package
--

[NOTE]
--
The 'start.sh' script consist out of a simple run script which launches the webplatform
[source, bash]
#!/usr/bin/env bash
node src/app.js
--
